/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    applicants: ApplicantAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    notices: Notice;
    highlights: Highlight;
    faculties: Faculty;
    programmes: Programme;
    'gallery-items': GalleryItem;
    media: Media;
    applications: Application;
    applicants: Applicant;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    notices: NoticesSelect<false> | NoticesSelect<true>;
    highlights: HighlightsSelect<false> | HighlightsSelect<true>;
    faculties: FacultiesSelect<false> | FacultiesSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    applicants: ApplicantsSelect<false> | ApplicantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'institute-settings': InstituteSetting;
  };
  globalsSelect: {
    'institute-settings': InstituteSettingsSelect<false> | InstituteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Applicant | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ApplicantAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Notices, advertisements, events and tenders shown on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices".
 */
export interface Notice {
  id: number;
  /**
   * The headline shown on the notice board.
   */
  title: string;
  category: 'Notice' | 'Advertisement' | 'Event' | 'Tender';
  /**
   * Date shown against the notice.
   */
  date: string;
  isNew?: boolean | null;
  /**
   * Optional PDF or image for this notice.
   */
  attachment?: (number | null) | Media;
  /**
   * Optional link, used only if no file is attached (e.g. an external portal).
   */
  externalUrl?: string | null;
  /**
   * Optional longer description.
   */
  body?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers (required for accessibility / GIGW).
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Photographs shown in the homepage highlights carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights".
 */
export interface Highlight {
  id: number;
  title: string;
  /**
   * One line describing the occasion.
   */
  caption: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * The faculties shown on the homepage and Academics page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculties".
 */
export interface Faculty {
  id: number;
  name: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  icon: 'lotus' | 'script' | 'herb' | 'compass';
  blurb: string;
  points?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Degrees offered, shown on the homepage, Academics and Admissions pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  title: string;
  level: 'Undergraduate' | 'Postgraduate' | 'Doctoral' | 'Professional';
  /**
   * e.g. 4 Years
   */
  duration?: string | null;
  order: number;
  note: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photographs shown in the homepage strip and the Gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  title: string;
  /**
   * Short label, e.g. Choglamsar, Residence.
   */
  tag: string;
  order: number;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admission applications submitted by applicants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  /**
   * Allocated automatically when the application is submitted.
   */
  applicationNumber?: string | null;
  /**
   * Setting this to 'Enrolled' creates the student record and allocates a student ID.
   */
  status: 'draft' | 'submitted' | 'under-review' | 'shortlisted' | 'admitted' | 'enrolled' | 'rejected';
  applicant: number | Applicant;
  programme: number | Programme;
  /**
   * Mirrored from the chosen programme; drives which sections apply.
   */
  level?: ('Undergraduate' | 'Postgraduate' | 'Doctoral' | 'Professional') | null;
  submittedAt?: string | null;
  fullName: string;
  email: string;
  phone: string;
  dateOfBirth?: string | null;
  gender?: ('female' | 'male' | 'other' | 'undisclosed') | null;
  fatherName?: string | null;
  nationality?: string | null;
  category?: ('General' | 'OBC' | 'SC' | 'ST' | 'EWS') | null;
  address?: string | null;
  district?: string | null;
  state?: string | null;
  pincode?: string | null;
  schooling?: {
    class10Board?: string | null;
    class10Year?: number | null;
    class10Percentage?: number | null;
    class12Board?: string | null;
    class12Year?: number | null;
    class12Percentage?: number | null;
    class12Stream?: string | null;
  };
  graduation?: {
    degree?: string | null;
    university?: string | null;
    year?: number | null;
    percentage?: number | null;
  };
  postGraduation?: {
    degree?: string | null;
    university?: string | null;
    year?: number | null;
    percentage?: number | null;
  };
  research?: {
    area?:
      | (
          | 'Buddhist Philosophy (Bhoti)'
          | 'Buddhist Philosophy (Sanskrit)'
          | 'Literature'
          | 'Comparative Philosophy'
          | 'History'
        )
      | null;
    synopsis?: string | null;
    netQualified?: boolean | null;
  };
  sowaRigpa?: {
    biologyStudied?: boolean | null;
    bhotiKnowledge?: ('None' | 'Basic' | 'Proficient') | null;
  };
  otherQualifications?: string | null;
  /**
   * Marksheets, certificates, ID proof, photograph.
   */
  documents?:
    | {
        type:
          | 'Photograph'
          | 'Class X Marksheet'
          | 'Class XII Marksheet'
          | 'Degree Certificate'
          | "Master's Marksheet"
          | 'ID Proof (Aadhaar/Passport)'
          | 'Category Certificate'
          | 'Migration / Transfer Certificate'
          | 'Other';
        file: number | Media;
        /**
         * Ticked by CIBS staff once checked.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  transfer?: {
    isTransfer?: boolean | null;
    previousInstitution?: string | null;
    reason?: string | null;
  };
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Accounts created by applicants. Staff can view but should not edit these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicants".
 */
export interface Applicant {
  id: number;
  fullName?: string | null;
  phone?: string | null;
  otpHash?: string | null;
  otpExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'applicants';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Full name of the staff member.
   */
  name: string;
  /**
   * Administrators can additionally manage user accounts.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'notices';
        value: number | Notice;
      } | null)
    | ({
        relationTo: 'highlights';
        value: number | Highlight;
      } | null)
    | ({
        relationTo: 'faculties';
        value: number | Faculty;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'applicants';
        value: number | Applicant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'applicants';
        value: number | Applicant;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'applicants';
        value: number | Applicant;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices_select".
 */
export interface NoticesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  date?: T;
  isNew?: T;
  attachment?: T;
  externalUrl?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights_select".
 */
export interface HighlightsSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  order?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculties_select".
 */
export interface FacultiesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  icon?: T;
  blurb?: T;
  points?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  level?: T;
  duration?: T;
  order?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  order?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  applicationNumber?: T;
  status?: T;
  applicant?: T;
  programme?: T;
  level?: T;
  submittedAt?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  dateOfBirth?: T;
  gender?: T;
  fatherName?: T;
  nationality?: T;
  category?: T;
  address?: T;
  district?: T;
  state?: T;
  pincode?: T;
  schooling?:
    | T
    | {
        class10Board?: T;
        class10Year?: T;
        class10Percentage?: T;
        class12Board?: T;
        class12Year?: T;
        class12Percentage?: T;
        class12Stream?: T;
      };
  graduation?:
    | T
    | {
        degree?: T;
        university?: T;
        year?: T;
        percentage?: T;
      };
  postGraduation?:
    | T
    | {
        degree?: T;
        university?: T;
        year?: T;
        percentage?: T;
      };
  research?:
    | T
    | {
        area?: T;
        synopsis?: T;
        netQualified?: T;
      };
  sowaRigpa?:
    | T
    | {
        biologyStudied?: T;
        bhotiKnowledge?: T;
      };
  otherQualifications?: T;
  documents?:
    | T
    | {
        type?: T;
        file?: T;
        verified?: T;
        id?: T;
      };
  transfer?:
    | T
    | {
        isTransfer?: T;
        previousInstitution?: T;
        reason?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicants_select".
 */
export interface ApplicantsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  otpHash?: T;
  otpExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, contact details and social links used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institute-settings".
 */
export interface InstituteSetting {
  id: number;
  name: string;
  shortName: string;
  /**
   * e.g. "Deemed to be University"
   */
  status: string;
  ministry: string;
  founded: number;
  tagline: string;
  phone: string;
  email: string;
  addressLine1: string;
  addressLine2: string;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institute-settings_select".
 */
export interface InstituteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  status?: T;
  ministry?: T;
  founded?: T;
  tagline?: T;
  phone?: T;
  email?: T;
  addressLine1?: T;
  addressLine2?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}